### ISSUE TITLE
Consistent DBConection.OwnershipError

### ISSUE THREAD

**Issue by k-cross** [elixir-ecto/myxql#76]
Using `propcheck` to generate some structures that we populate to a json field in the database (mysql 5.7.27), we consistently run into this problem.

Unfortunately, I'm not really sure what to do about this output, it's pretty cryptic but I am willing to help in whatever capacity I can. We still haven't switched from `mariaex` so maybe there is some behavior difference happening here. I can say the the output is not larger than 65kb.

```
Failed: After 1808 test(s).
An exception was raised: error:#{'__exception__' => true,'__struct__' => 'Elixir.DBConnection.OwnershipError',message => <<99,97,110,110,111,116,32,102,105,110,100,32,111,119,110,101,114,115,104,105,112,32,112,114,111,99,101,115,115,32,102,111,114,32,35,80,73,68,60,48,46,57,50,48,46,48,62,46,10,10,87,104,101,110,32,117,115,105,110,103,32,111,119,110,101,114,115,104,105,112,44,32,121,111,117,32,109,117,115,116,32,109,97,110,97,103,101,32,99,111,110,110,101,99,116,105,111,110,115,32,105,110,32,111,110,101,10,111,102,32,116,104,101,32,102,111,117,114,32,119,97,121,115,58,10,10,42,32,66,121,32,101,120,112,108,105,99,105,116,108,121,32,99,104,101,99,107,105,110,103,32,111,117,116,32,97,32,99,111,110,110,101,99,116,105,111,110,10,42,32,66,121,32,101,120,112,108,105,99,105,116,108,121,32,97,108,108,111,119,105,110,103,32,97,32,115,112,97,119,110,101,100,32,112,114,111,99,101,115,115,10,42,32,66,121,32,114,117,110,110,105,110,103,32,116,104,101,32,112,111,111,108,32,105,110,32,115,104,97,114,101,100,32,109,111,100,101,10,42,32,66,121,32,117,115,105,110,103,32,58,99,97,108,108,101,114,32,111,112,116,105,111,110,32,119,105,116,104,32,97,108,108,111,119,101,100,32,112,114,111,99,101,115,115,10,10,84,104,101,32,102,105,114,115,116,32,116,119,111,32,111,112,116,105,111,110,115,32,114,101,113,117,105,114,101,32,101,118,101,114,121,32,110,101,119,32,112,114,111,99,101,115,115,32,116,111,32,101,120,112,108,105,99,105,116,108,121,10,99,104,101,99,107,32,97,32,99,111,110,110,101,99,116,105,111,110,32,111,117,116,32,111,114,32,98,101,32,97,108,108,111,119,101,100,32,98,121,32,99,97,108,108,105,110,103,32,99,104,101,99,107,111,117,116,32,111,114,10,97,108,108,111,119,32,114,101,115,112,101,99,116,105,118,101,108,121,46,10,10,84,104,101,32,116,104,105,114,100,32,111,112,116,105,111,110,32,114,101,113,117,105,114,101,115,32,97,32,123,58,115,104,97,114,101,100,44,32,112,105,100,125,32,109,111,100,101,32,116,111,32,98,101,32,115,101,116,46,10,73,102,32,117,115,105,110,103,32,115,104,97,114,101,100,32,109,111,100,101,32,105,110,32,116,101,115,116,115,44,32,109,97,107,101,32,115,117,114,101,32,121,111,117,114,32,116,101,115,116,115,32,97,114,101,32,110,111,116,10,97,115,121,110,99,46,10,10,84,104,101,32,102,111,117,114,116,104,32,111,112,116,105,111,110,32,114,101,113,117,105,114,101,115,32,91,99,97,108,108,101,114,58,32,112,105,100,93,32,116,111,32,98,101,32,117,115,101,100,32,119,104,101,110,10,99,104,101,99,107,105,110,103,32,111,117,116,32,97,32,99,111,110,110,101,99,116,105,111,110,32,102,114,111,109,32,116,104,101,32,112,111,111,108,46,32,84,104,101,32,99,97,108,108,101,114,32,112,114,111,99,101,115,115,10,115,104,111,117,108,100,32,97,108,114,101,97,100,121,32,98,101,32,97,108,108,111,119,101,100,32,111,110,32,97,32,99,111,110,110,101,99,116,105,111,110,46,10,10,73,102,32,121,111,117,32,97,114,101,32,114,101,97,100,105,110,103,32,116,104,105,115,32,101,114,114,111,114,44,32,105,116,32,109,101,97,110,115,32,121,111,117,32,104,97,118,101,32,110,111,116,32,100,111,110,101,32,111,110,101,10,111,102,32,116,104,101,32,115,116,101,112,115,32,97,98,111,118,101,32,111,114,32,116,104,97,116,32,116,104,101,32,111,119,110,101,114,32,112,114,111,99,101,115,115,32,104,97,115,32,99,114,97,115,104,101,100,46,10,10,83,101,101,32,69,99,116,111,46,65,100,97,112,116,101,114,115,46,83,81,76,46,83,97,110,100,98,111,120,32,100,111,99,115,32,102,111,114,32,109,111,114,101,32,105,110,102,111,114,109,97,116,105,111,110,46>>}.
```

**Comment by wojtekmach** [comment]
Thank you for the report.

FWIW: 

```
iex> <<99,97,110,110,111,116, (...)>>
"cannot find ownership process for #PID<0.920.0>.\n\nWhen using ownership, you must manage connections in one\nof the four ways:\n\n* By explicitly checking out a connection\n* By explicitly allowing a spawned process\n* By running the pool in shared mode\n* By using :caller option with allowed process\n\nThe first two options require every new process to explicitly\ncheck a connection out or be allowed by calling checkout or\nallow respectively.\n\nThe third option requires a {:shared, pid} mode to be set.\nIf using shared mode in tests, make sure your tests are not\nasync.\n\nThe fourth option requires [caller: pid] to be used when\nchecking out a connection from the pool. The caller process\nshould already be allowed on a connection.\n\nIf you are reading this error, it means you have not done one\nof the steps above or that the owner process has crashed.\n\nSee Ecto.Adapters.SQL.Sandbox docs for more information."
```

If it worked on mariaex but not on myxql, it's definitely a bug here. Any chance you could narrow it down to a minimal project we could run ourselves?

**Comment by k-cross** [comment]
I'll try to make something that I can pass along sometime later this week.

Just in case I don't get to it in a timely manner, I suspect that you can generate maps in a property testing framework of your choice to a column in a table and up the count to around 10,000. Mine have never made it past 2500 but there is a lot of domain knowledge being stored here.

**Comment by k-cross** [comment]
https://github.com/k-cross/xql_verify

I provided instructions in the `readme` but it is very straight forward.

**Comment by wojtekmach** [comment]
Thank you @k-cross. I was getting a bunch of errors like:

```
** (StreamData.TooManyDuplicatesError) too many (10) non-unique elements were generated consecutively.
```

but I could see the error with this generator:

```
check all foo_map <- map_of(binary(), binary(), min_length: 0)
```

Here's my output:

```
13:13:53.115 [debug] QUERY OK db=2.8ms decode=0.6ms queue=1.9ms
INSERT INTO `foo` (`bar`) VALUES (?) [%{"\a" => "P"}]

13:13:53.120 [debug] QUERY ERROR db=3.7ms
INSERT INTO `foo` (`bar`) VALUES (?) [%{"" => <<252, 141>>}]

13:13:53.121 [debug] QUERY ERROR queue=1.3ms
INSERT INTO `foo` (`bar`) VALUES (?) [%{}]

13:13:53.121 [debug] QUERY ERROR
INSERT INTO `foo` (`bar`) VALUES (?) [%{"" => <<141>>}]

13:13:53.122 [debug] QUERY ERROR
INSERT INTO `foo` (`bar`) VALUES (?) [%{}]

13:13:53.122 [debug] QUERY ERROR
INSERT INTO `foo` (`bar`) VALUES (?) [%{"" => ""}]

13:13:53.122 [debug] QUERY ERROR
INSERT INTO `foo` (`bar`) VALUES (?) [%{}]

13:13:53.123 [error] GenServer #PID<0.248.0> terminating
** (DBConnection.ConnectionError) client #PID<0.284.0> stopped: ** (Jason.EncodeError) invalid byte 0xFC in <<252, 141>>
    (jason 1.1.2) lib/jason.ex:150: Jason.encode!/2
    (myxql 0.2.7) lib/myxql/protocol/values.ex:220: MyXQL.Protocol.Values.encode_binary_value/1

(...)

         ** (DBConnection.OwnershipError) cannot find ownership process for #PID<0.284.0>.

(...)
```

I wonder if you were getting any other errors before the ownership one?

**Comment by wojtekmach** [comment]
Btw, here are stack traces:

mariaex:

```
     stacktrace:
       (jason 1.1.2) lib/jason.ex:199: Jason.encode_to_iodata!/2
       (ecto_sql 3.1.6) lib/ecto/adapters/mysql/connection.ex:985: Ecto.Adapters.MySQL.Connection.json_encode!/1
```

myxql:

```
13:28:55.341 [error] GenServer #PID<0.223.0> terminating
** (DBConnection.ConnectionError) client #PID<0.254.0> stopped: ** (Jason.EncodeError) invalid byte 0xE8 in <<232>>

     stacktrace:
       (ecto_sql 3.1.6) lib/ecto/adapters/myxql.ex:208: Ecto.Adapters.MyXQL.insert/6
```

the difference here is mariaex-based adapter encodes Jason in the adapter so the driver isn't even hit, whereas with myxql Jason encoding happens in the driver. And because there was a Jason error the connection crashed. The solution would be to gracefully handle Jason errors which I'll work I the meantime.

**Comment by wojtekmach** [comment]
@k-cross I published a bug fix in v0.2.8, please give it a try and let us know if it solves your issue.

**Comment by k-cross** [comment]
Hmm, I'll take a closer look on Monday but I still get an issue, seems to be a little different now though.

```
An exception was raised: exit:{{shutdown,#{'__exception__' => true,'__struct__' => 'Elixir.DBConnection.ConnectionError',message => <<111,119,110,101,114,32,35,80,73,68,60,48,46,57,50,48,46,48,62,32,116,105,109,101,100,32,111,117,116,32,98,101,99,97,117,115,101,32,105,116,32,111,119,110,101,100,32,116,104,101,32,99,111,110,110,101,99,116,105,111,110,32,102,111,114,32,108,111,110,103,101,114,32,116,104,97,110,32,54,48,48,48,48,109,115,32,40,115,101,116,32,118,105,97,32,116,104,101,32,58,111,119,110,101,114,115,104,105,112,95,116,105,109,101,111,117,116,32,111,112,116,105,111,110,41>>,severity => error}},{'Elixir.DBConnection.Holder',checkout,[<0.922.0>,[{query_type,binary_then_text},{log,#Fun<Elixir.Ecto.Adapters.SQL.11.109787599>},{source,<<116,101,109,112,108,97,116,101>>},{timeout,15000},{pool_size,10},{pool,'Elixir.DBConnection.Ownership'}]]}}
```

**Comment by k-cross** [comment]
Okay, looking into this a little more it seems like we get more errors because responses are slower than they once were so we get more timeout errors. This is not great but I can keep tracking more issues.

Also, I updated the project to reproduce output that's able to directly convert to json. It's not ideal, but it might be nice to try to switch back to an older version of `ecto_sql` just so I can use the `mariaex` DB adapter in order to perform comparisons so that we can easily do equality testing.

```
"owner #PID<0.920.0> timed out because it owned the connection for longer than 60000ms (set via the :ownership_timeout option)"
```

**Comment by josevalim** [comment]
Btw, See #60 for the speed up discussions.
